# -*- coding: utf-8 -*-
"""Ishara_VDzSL_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUJ-wiF9tGb1ZHWXfLj7GtloVJ--VOoy

# Ishara — VDzSL → trained model (Google Drive + T4)

Put `VDzSL.zip` directly in **Google Drive → My Drive**.

Use a **T4 GPU** in Colab, then run cells from top to bottom.
"""

# ================================================================
# CELL 1 -- SETUP (run once per fresh runtime)
# ================================================================
!pip -q install mediapipe onnx onnxruntime

from google.colab import drive
from pathlib import Path
import os, json, zipfile, shutil, random, time
import cv2, numpy as np, mediapipe as mp
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

drive.mount('/content/drive')

ZIP_PATH = Path('/content/drive/MyDrive/ISHARA-Datasets/VDzSL.zip')
if not ZIP_PATH.exists():
    raise FileNotFoundError('Put VDzSL.zip directly in My Drive/ISHARA-Datasets/.')
print('Found:', ZIP_PATH, '|', round(ZIP_PATH.stat().st_size/1024**3, 2), 'GB')

print('GPU:', torch.cuda.is_available())

DATA_ROOT = Path('/content/VDzSL_dataset')
if DATA_ROOT.exists():
    shutil.rmtree(DATA_ROOT)
DATA_ROOT.mkdir()

print('Extracting dataset zip (this always re-runs, /content is wiped each session)...')
t = time.time()
with zipfile.ZipFile(ZIP_PATH) as z:
    z.extractall(DATA_ROOT)
print('Done:', round((time.time() - t) / 60, 1), 'min')

VIDEO_EXT = {'.mp4', '.avi', '.mov', '.mkv', '.webm'}
def get_part(parts, prefix):
    return next((x for x in parts if x.lower().startswith(prefix)), None)

records = []
for p in DATA_ROOT.rglob('*'):
    if p.is_file() and p.suffix.lower() in VIDEO_EXT:
        records.append({'path': str(p), 'label': p.stem.strip(),
                         'signer': get_part(p.parts, 'signer'),
                         'camera': get_part(p.parts, 'cam')})

signers = sorted({r['signer'] for r in records if r['signer']},
                  key=lambda x: int(''.join(filter(str.isdigit, x)) or 999))
labels = sorted({r['label'] for r in records})
label_to_id = {x: i for i, x in enumerate(labels)}

TEST_SIGNER = signers[-1]
for r in records:
    r['label_id'] = label_to_id[r['label']]

print('Videos:', len(records), '| Classes:', len(labels), '| Signers:', signers)
print('Held-out unseen-signer check:', TEST_SIGNER)

# ================================================================
# CELL 2 (REPLACEMENT) -- FEATURE EXTRACTION via Tasks API
# (mp.solutions.holistic no longer exists in current mediapipe --
#  this uses PoseLandmarker + HandLandmarker instead, same API
#  family your web app already uses)
# ================================================================
#
# NORMALIZATION (write this down -- your app must match it exactly):
#   center = midpoint of pose landmarks 23 (L hip) and 24 (R hip)
#   scale  = distance between pose landmarks 11 (L shoulder) and 12 (R shoulder)
#   (point - center) / max(scale, 1e-4), applied to pose + both hands
#
# Feature layout (258 floats/frame):
#   [0:132]   pose  33 landmarks x (x,y,z,visibility)
#   [132:195] left hand  21 landmarks x (x,y,z)      -- no visibility
#   [195:258] right hand 21 landmarks x (x,y,z)      -- no visibility

import urllib.request
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision

FRAMES = 16
FEATURES = 258

MODEL_DIR = Path('/content/mp_models')
MODEL_DIR.mkdir(exist_ok=True)
POSE_MODEL = MODEL_DIR / 'pose_landmarker_lite.task'
HAND_MODEL = MODEL_DIR / 'hand_landmarker.task'

if not POSE_MODEL.exists():
    urllib.request.urlretrieve(
        'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task',
        POSE_MODEL)
if not HAND_MODEL.exists():
    urllib.request.urlretrieve(
        'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',
        HAND_MODEL)
print('Models ready.')

pose_landmarker = vision.PoseLandmarker.create_from_options(vision.PoseLandmarkerOptions(
    base_options=mp_python.BaseOptions(model_asset_path=str(POSE_MODEL)),
    running_mode=vision.RunningMode.IMAGE, num_poses=1))
hand_landmarker = vision.HandLandmarker.create_from_options(vision.HandLandmarkerOptions(
    base_options=mp_python.BaseOptions(model_asset_path=str(HAND_MODEL)),
    running_mode=vision.RunningMode.IMAGE, num_hands=2))

def frame_features(rgb):
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
    pose_result = pose_landmarker.detect(mp_image)
    hand_result = hand_landmarker.detect(mp_image)

    pose = np.zeros((33, 4), np.float32)
    if pose_result.pose_landmarks:
        for i, lm in enumerate(pose_result.pose_landmarks[0]):
            pose[i] = [lm.x, lm.y, lm.z, getattr(lm, 'visibility', 1.0)]

    left, right = np.zeros((21, 3), np.float32), np.zeros((21, 3), np.float32)
    if hand_result.hand_landmarks:
        for hand_lm, handedness in zip(hand_result.hand_landmarks, hand_result.handedness):
            pts = np.array([[lm.x, lm.y, lm.z] for lm in hand_lm], np.float32)
            if handedness[0].category_name == 'Left':
                left = pts
            else:
                right = pts

    center = (pose[23, :3] + pose[24, :3]) / 2 if np.any(pose[23, :3]) and np.any(pose[24, :3]) else np.array([.5, .5, 0], np.float32)
    scale = max(float(np.linalg.norm(pose[11, :3] - pose[12, :3])), 1e-4)
    for a in (pose, left, right):
        a[:, :3] = (a[:, :3] - center) / scale
    return np.concatenate([pose.ravel(), left.ravel(), right.ravel()]).astype(np.float32)

DEBUG_PRINTED = 0

def extract_video(path):
    global DEBUG_PRINTED
    cap = cv2.VideoCapture(path)
    if not cap.isOpened():
        if DEBUG_PRINTED < 3:
            print('DEBUG: could not open ->', path)
            DEBUG_PRINTED += 1
        cap.release()
        return None

    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total <= 0:
        # CAP_PROP_FRAME_COUNT is unreliable for some containers -- count manually.
        count = 0
        while True:
            ok = cap.grab()
            if not ok:
                break
            count += 1
        total = count
        cap.release()
        cap = cv2.VideoCapture(path)  # reopen to read from the start
        if DEBUG_PRINTED < 3:
            print(f'DEBUG: frame count unreliable, manually counted {total} frames ->', path)
            DEBUG_PRINTED += 1

    if total <= 0:
        if DEBUG_PRINTED < 3:
            print('DEBUG: zero frames even after manual count ->', path)
            DEBUG_PRINTED += 1
        cap.release()
        return None

    idxs = set(np.linspace(0, total - 1, FRAMES).astype(int).tolist())
    out = []
    frame_i = 0
    grabbed = {}
    # sequential read + selective decode -- more robust than POS_FRAMES seeking
    # for containers with unreliable seek tables.
    while len(grabbed) < len(idxs):
        ok = cap.grab()
        if not ok:
            break
        if frame_i in idxs:
            ok2, frame = cap.retrieve()
            if ok2:
                grabbed[frame_i] = frame
        frame_i += 1
    cap.release()

    for idx in sorted(idxs):
        frame = grabbed.get(idx)
        if frame is None:
            out.append(np.zeros(FEATURES, np.float32))
        else:
            out.append(frame_features(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)))

    arr = np.asarray(out, np.float32)
    return arr if arr.shape == (FRAMES, FEATURES) else None
# Drive-backed cache -- one-time-ever cost, survives restarts.
CACHE = Path('/content/drive/MyDrive/ISHARA-Datasets/VDzSL_cache_258')
CACHE.mkdir(parents=True, exist_ok=True)

usable = []
already = 0
start = time.time()
for i, r0 in enumerate(records):
    out_path = CACHE / f'{i}.npy'
    if out_path.exists():
        usable.append(dict(r0, cache=str(out_path)))
        already += 1
        continue
    try:
        x = extract_video(r0['path'])
        if x is not None:
            np.save(out_path, x)
            usable.append(dict(r0, cache=str(out_path)))
    except Exception as e:
        print('FAILED:', r0['path'], repr(e))
    if (i + 1) % 100 == 0:
        elapsed = time.time() - start
        rate = max((i + 1 - already), 1) / max(elapsed, 1)
        eta = (len(records) - i - 1) / rate / 60
        print(f'{i+1}/{len(records)} | already cached: {already} | ~{rate:.2f} new/s | ETA {eta:.1f} min')

print(f'Usable: {len(usable)} / {len(records)}  ({already} were already cached on Drive)')

# ================================================================
# CELL 3 (v3) -- SIGNER-SAFE SPLITS + SMARTER AUGMENTATION + VELOCITY FEATURES
# ================================================================
from collections import defaultdict

# IMPORTANT: choose the unseen signer BEFORE creating train/validation splits.
# The previous version split all records first, then merely reported the
# selected signer's records. That leaked the test signer into training.
if not TEST_SIGNER:
    raise RuntimeError('No signer was detected; cannot run a signer-held-out evaluation.')

unseen_signer_records = [r for r in usable if r.get('signer') == TEST_SIGNER]
development_records = [r for r in usable if r.get('signer') != TEST_SIGNER]
if not unseen_signer_records:
    raise RuntimeError(f'No usable records found for held-out signer: {TEST_SIGNER}')
if not development_records:
    raise RuntimeError('No development records remain after holding out the test signer.')

# Stratify validation by label, but only within non-test signers.
by_label = defaultdict(list)
for r in development_records:
    by_label[r['label_id']].append(r)

train_records, val_records = [], []
split_rng = random.Random(42)
for _, items in by_label.items():
    split_rng.shuffle(items)
    # Keep at least one development example in training whenever possible.
    n_val = max(1, int(len(items) * 0.15)) if len(items) > 1 else 0
    val_records.extend(items[:n_val])
    train_records.extend(items[n_val:])

train_labels = {r['label_id'] for r in train_records}
validation_only_labels = sorted({r['label_id'] for r in val_records} - train_labels)
unseen_only_labels = sorted({r['label_id'] for r in unseen_signer_records} - train_labels)
unseen_eval_records = [
    r for r in unseen_signer_records if r['label_id'] in train_labels
]

print('Signer-safe train:', len(train_records), '| val:', len(val_records),
      '| held-out signer:', TEST_SIGNER,
      '| unseen-signer test:', len(unseen_signer_records))
print('Unique signers in train:', sorted({r.get('signer') for r in train_records}))
print('Unique signers in val:', sorted({r.get('signer') for r in val_records}))
print('Labels with no training examples in validation:', len(validation_only_labels))
print('Labels with no training examples in held-out signer:', len(unseen_only_labels))
print('Held-out records with known training labels:', len(unseen_eval_records),
      '/', len(unseen_signer_records))
if validation_only_labels:
    print('WARNING: validation-only labels:', [labels[i] for i in validation_only_labels[:20]])
if unseen_only_labels:
    print('WARNING: unseen-signer-only labels:', [labels[i] for i in unseen_only_labels[:20]])

signer_to_id = {s: i for i, s in enumerate(signers)}
NUM_SIGNERS = len(signers)

MODEL_INPUT_SIZE = FEATURES * 2  # raw (258) + velocity (258) = 516

def rotate_xy(a, angle_rad):
    c, s = math.cos(angle_rad), math.sin(angle_rad)
    x, y = a[..., 0].copy(), a[..., 1].copy()
    a[..., 0] = x * c - y * s
    a[..., 1] = x * s + y * c
    return a

class SignDataset(Dataset):
    def __init__(self, rs, augment=False):
        self.rs, self.augment = rs, augment

    def __len__(self):
        return len(self.rs)

    def __getitem__(self, i):
        r = self.rs[i]
        x = np.load(r['cache']).copy()  # (16, 258)
        pose = x[:, :132].reshape(16, 33, 4)
        left = x[:, 132:195].reshape(16, 21, 3)
        right = x[:, 195:258].reshape(16, 21, 3)

        if self.augment:
            # -- mirror (disable if handedness is semantically meaningful) --
            if random.random() < 0.5:
                for a in (pose, left, right):
                    a[..., 0] *= -1
                left, right = right.copy(), left.copy()

            # -- simulated camera tilt --
            if random.random() < 0.5:
                angle = math.radians(random.uniform(-8, 8))
                for a in (pose, left, right):
                    rotate_xy(a[..., :3], angle)

            # -- simulated distance-from-camera jitter --
            if random.random() < 0.5:
                scale = random.uniform(0.9, 1.1)
                for a in (pose, left, right):
                    a[..., :3] *= scale

            # -- simulated off-center framing --
            if random.random() < 0.4:
                off = np.random.uniform(-0.05, 0.05, size=2).astype(np.float32)
                for a in (pose, left, right):
                    a[..., 0] += off[0]
                    a[..., 1] += off[1]

            # -- simulated dropped hand tracking (real MediaPipe failure mode) --
            if random.random() < 0.15:
                left[:] = 0
            if random.random() < 0.15:
                right[:] = 0

            # -- mild temporal jitter: hold a pose one frame longer --
            if random.random() < 0.3:
                idx = random.randint(1, 14)
                pose[idx] = pose[idx - 1]
                left[idx] = left[idx - 1]
                right[idx] = right[idx - 1]

            # -- gaussian sensor noise --
            if random.random() < 0.45:
                for a in (pose, left, right):
                    a[..., :3] += np.random.randn(*a[..., :3].shape).astype(np.float32) * 0.008

        raw = np.concatenate([pose.reshape(16, -1), left.reshape(16, -1), right.reshape(16, -1)], axis=1)
        velocity = np.diff(raw, axis=0, prepend=raw[0:1])
        full = np.concatenate([raw, velocity], axis=1).astype(np.float32)  # (16, 516)

        signer_id = signer_to_id.get(r.get('signer'), 0)
        return (torch.tensor(full, dtype=torch.float32),
                torch.tensor(r['label_id'], dtype=torch.long),
                torch.tensor(signer_id, dtype=torch.long))

# Pinned host memory only helps when batches are copied to a CUDA device.
# Colab can start on CPU (or lose its runtime accelerator), so derive this
# from the runtime instead of emitting a misleading warning on every epoch.
PIN_MEMORY = torch.cuda.is_available()
train_loader = DataLoader(SignDataset(train_records, augment=True), batch_size=64, shuffle=True, num_workers=2, pin_memory=PIN_MEMORY)
val_loader = DataLoader(SignDataset(val_records), batch_size=64, num_workers=2, pin_memory=PIN_MEMORY)
unseen_loader = DataLoader(SignDataset(unseen_eval_records), batch_size=64, num_workers=2, pin_memory=PIN_MEMORY) if unseen_eval_records else None

# ================================================================
# CELL 4 (v2) -- MODEL WITH DOMAIN-ADVERSARIAL (SIGNER-INVARIANT) HEAD
# ================================================================
import math, copy

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USE_AMP = DEVICE.type == 'cuda'
NUM_CLASSES = len(labels)

class GradientReversal(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, alpha):
        ctx.alpha = alpha
        return x.view_as(x)
    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.alpha * grad_output, None

def grad_reverse(x, alpha):
    return GradientReversal.apply(x, alpha)

class IsharaFinal(nn.Module):
    def __init__(self, n_classes, n_signers, input_size):
        super().__init__()
        self.input_norm = nn.LayerNorm(input_size)
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=192, num_layers=2,
                             batch_first=True, bidirectional=True, dropout=0.30)
        self.attention = nn.Sequential(nn.Linear(384, 128), nn.Tanh(), nn.Linear(128, 1))
        self.classifier = nn.Sequential(
            nn.LayerNorm(768), nn.Linear(768, 384), nn.GELU(), nn.Dropout(0.35),
            nn.Linear(384, 192), nn.GELU(), nn.Dropout(0.25), nn.Linear(192, n_classes))
        # signer-discriminator head -- trained adversarially via grad_reverse
        # so the SHARED features become signer-invariant, not signer-predictive.
        self.domain_head = nn.Sequential(
            nn.Linear(768, 128), nn.ReLU(), nn.Dropout(0.3), nn.Linear(128, n_signers))

    def forward(self, x, alpha=0.0):
        x = self.input_norm(x)
        y, _ = self.lstm(x)
        w = torch.softmax(self.attention(y), dim=1)
        attn_pool = torch.sum(w * y, dim=1)
        max_pool = torch.max(y, dim=1).values
        features = torch.cat([attn_pool, max_pool], dim=1)
        class_logits = self.classifier(features)
        domain_logits = self.domain_head(grad_reverse(features, alpha))
        return class_logits, domain_logits

model = IsharaFinal(NUM_CLASSES, NUM_SIGNERS, MODEL_INPUT_SIZE).to(DEVICE)
print('Parameters:', f'{sum(p.numel() for p in model.parameters()):,}')

EPOCHS, MAX_LR, MIN_LR, WD, WARMUP, PATIENCE = 150, 1e-3, 1e-5, 1e-4, 8, 25
DOMAIN_LOSS_WEIGHT = 0.2   # keep the adversarial signal secondary to the main task
BEST_PATH = '/content/ishara_FINAL_best.pt'
criterion = nn.CrossEntropyLoss(label_smoothing=0.05)
domain_criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=MAX_LR, weight_decay=WD)
scaler = torch.amp.GradScaler('cuda', enabled=USE_AMP)

def get_lr(epoch):
    if epoch <= WARMUP:
        return MIN_LR + (MAX_LR - MIN_LR) * (epoch / WARMUP)
    prog = (epoch - WARMUP) / (EPOCHS - WARMUP)
    return MIN_LR + (MAX_LR - MIN_LR) * 0.5 * (1 + math.cos(math.pi * prog))

def get_alpha(epoch):
    # standard DANN ramp: 0 -> 1 over training, so early epochs focus on
    # learning the task at all before asking for signer-invariance too.
    p = epoch / EPOCHS
    return (2.0 / (1.0 + math.exp(-10 * p)) - 1.0)

ema_model = copy.deepcopy(model)
for p in ema_model.parameters(): p.requires_grad_(False)
EMA_DECAY = 0.999

@torch.no_grad()
def update_ema():
    for ep, mp_ in zip(ema_model.parameters(), model.parameters()):
        ep.mul_(EMA_DECAY).add_(mp_, alpha=1 - EMA_DECAY)

def train_one_epoch(loader, alpha):
    model.train()
    total = correct = 0; loss_sum = 0.0
    epoch_start = time.time()
    total_batches = len(loader)
    for batch_index, (x, y, signer_id) in enumerate(loader, start=1):
        x = x.to(DEVICE, non_blocking=True)
        y = y.to(DEVICE, non_blocking=True)
        signer_id = signer_id.to(DEVICE, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast(device_type='cuda', enabled=USE_AMP):
            class_logits, domain_logits = model(x, alpha=alpha)
            loss = criterion(class_logits, y) + DOMAIN_LOSS_WEIGHT * domain_criterion(domain_logits, signer_id)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer); scaler.update()
        update_ema()
        loss_sum += loss.item() * len(y)
        correct += (class_logits.argmax(1) == y).sum().item()
        total += len(y)
        if batch_index == 1 or batch_index % 10 == 0 or batch_index == total_batches:
            elapsed = time.time() - epoch_start
            rate = batch_index / max(elapsed, 1e-6)
            remaining = max(total_batches - batch_index, 0) / max(rate, 1e-6)
            print(
                f"  batch {batch_index:03d}/{total_batches} | "
                f"loss={loss.item():.4f} | "
                f"elapsed={elapsed / 60:.1f}m | ETA={remaining / 60:.1f}m",
                flush=True,
            )
    return loss_sum / total, correct / total

@torch.no_grad()
def evaluate(loader, eval_model):
    eval_model.eval()
    total = correct = 0
    for x, y, _ in loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        class_logits, _ = eval_model(x, alpha=0.0)
        correct += (class_logits.argmax(1) == y).sum().item()
        total += len(y)
    return correct / total if total else 0.0

best_val, best_epoch, no_improve = -1.0, 0, 0
for epoch in range(1, EPOCHS + 1):
    lr = get_lr(epoch)
    for g in optimizer.param_groups: g['lr'] = lr
    alpha = get_alpha(epoch)
    train_loss, train_acc = train_one_epoch(train_loader, alpha)
    val_acc = evaluate(val_loader, model)
    ema_val_acc = evaluate(val_loader, ema_model)
    eval_acc = max(val_acc, ema_val_acc)
    eval_model = ema_model if ema_val_acc >= val_acc else model
    print(f'Epoch {epoch:03d}/{EPOCHS} | train={train_acc:.2%} | val={val_acc:.2%} | EMA={ema_val_acc:.2%} | alpha={alpha:.2f} | lr={lr:.2e}')
    if eval_acc > best_val:
        best_val, best_epoch, no_improve = eval_acc, epoch, 0
        torch.save({'epoch': epoch, 'model_state_dict': eval_model.state_dict(),
                    'best_val_acc': best_val, 'labels': labels}, BEST_PATH)
        print(f'    NEW BEST: {best_val:.2%}')
    else:
        no_improve += 1
    if no_improve >= PATIENCE:
        print(f'Early stopping at epoch {epoch}. Best: {best_val:.2%} (epoch {best_epoch})')
        break

checkpoint = torch.load(BEST_PATH, map_location=DEVICE)
model.load_state_dict(checkpoint['model_state_dict'])
final_val_acc = evaluate(val_loader, model)
final_unseen_acc = evaluate(unseen_loader, model) if unseen_loader else None

print()
print('=' * 70)
print(f'Stratified validation accuracy : {final_val_acc:.2%}')
if final_unseen_acc is not None:
    print(f"Unseen-signer ('{TEST_SIGNER}') accuracy : {final_unseen_acc:.2%} "
          f"(known-label coverage: {len(unseen_eval_records)}/{len(unseen_signer_records)})")
print('=' * 70)

# ================================================================
# CELL 5 (v2) -- EXPORT (class head only -- domain head was training-only)
# ================================================================
import json, shutil
import onnx
from google.colab import files

ONNX_PATH, LABELS_PATH, METADATA_PATH = '/content/model.onnx', '/content/labels.json', '/content/metadata.json'
OUT = Path('/content/ishara-model')

class ExportWrapper(nn.Module):
    """Strips the domain head -- deployment only ever needs sign classification."""
    def __init__(self, base_model):
        super().__init__()
        self.base = base_model
    def forward(self, x):
        class_logits, _ = self.base(x, alpha=0.0)
        return class_logits

model.eval().cpu()
export_model = ExportWrapper(model)
torch.onnx.export(export_model, torch.randn(1, FRAMES, MODEL_INPUT_SIZE), ONNX_PATH,
                   input_names=['landmarks'], output_names=['logits'], opset_version=17, dynamo=False)
onnx.checker.check_model(onnx.load(ONNX_PATH))

with open(LABELS_PATH, 'w', encoding='utf-8') as f:
    json.dump({str(i): labels[i] for i in range(NUM_CLASSES)}, f, ensure_ascii=False, indent=2)

metadata = {
    'dataset': 'VDzSL', 'model': 'IsharaFinal-v2-domain-adversarial',
    'architecture': 'LayerNorm(516) -> 2-layer BiLSTM(192, bidirectional) -> Temporal Attention + Max Pooling -> MLP Classifier (domain-adversarial signer head used only during training, not exported)',
    'classes': NUM_CLASSES, 'frames': FRAMES, 'features_per_frame': MODEL_INPUT_SIZE,
    'input_shape': [1, FRAMES, MODEL_INPUT_SIZE], 'input_name': 'landmarks', 'output_name': 'logits',
    'opset_version': 17, 'best_epoch': int(checkpoint.get('epoch', 0)),
    'stratified_validation_accuracy': final_val_acc,
    'unseen_signer_test_accuracy': final_unseen_acc,
    'unseen_signer': TEST_SIGNER,
    'unseen_signer_known_label_coverage': (
        len(unseen_eval_records) / len(unseen_signer_records)
        if unseen_signer_records else 0.0
    ),
    'feature_layout': {
        'raw_258': {
            'pose': '[0:132] 33 landmarks x (x,y,z,visibility)',
            'left_hand': '[132:195] 21 landmarks x (x,y,z)',
            'right_hand': '[195:258] 21 landmarks x (x,y,z)'
        },
        'velocity_258': '[258:516] frame-to-frame delta of the raw_258 block, same layout, first frame delta = 0'
    },
    'normalization': {
        'center': 'midpoint of pose landmarks 23 (L hip) and 24 (R hip)',
        'scale': 'distance between pose landmarks 11 (L shoulder) and 12 (R shoulder)',
        'applied_to': 'pose xyz, left hand xyz, right hand xyz -- NOT visibility',
        'formula': '(point - center) / max(scale, 1e-4)',
        'velocity_formula': 'raw[frame] - raw[frame-1], with raw[0] velocity = 0'
    }
}
with open(METADATA_PATH, 'w', encoding='utf-8') as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

if OUT.exists(): shutil.rmtree(OUT)
OUT.mkdir(parents=True)
for src in [ONNX_PATH, LABELS_PATH, METADATA_PATH]:
    shutil.copy(src, OUT / Path(src).name)
zip_out = shutil.make_archive('/content/ishara-model', 'zip', OUT)
print('Package ready:', zip_out)
files.download(zip_out)